-- Until I get the installer up and running, this will be how we deal with SQL updates.
-- The updates to the database structure and content are in this file.
-- Please make sure you've inserted sql_base.sql and then sql_data.sql information first.
-- Also, make sure to only run the most recent updates.